In [38]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import math
import seaborn as sns
import sklearn
from sklearn import linear_model
from sklearn import preprocessing
%matplotlib inline
sns.set_style('white')
from sklearn.linear_model import LogisticRegression
import statsmodels.discrete.discrete_model as sm

In [2]:
file = 'C:/Users/Greg/Documents/Personal/Thinkful/dsprojects/prepcap/Scorecard_Final.csv'
df = pd.read_csv(file)
display(df.shape)
df.head()

c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (4,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


(72032, 41)

Id  UNITID                               INSTNM STABBR AccredAgency  \
0  52668  100654             ALABAMA A & M UNIVERSITY     AL          NaN   
1  52669  100663  UNIVERSITY OF ALABAMA AT BIRMINGHAM     AL          NaN   
2  52670  100690                   Amridge University     AL          NaN   
3  52671  100706  University of Alabama in Huntsville     AL          NaN   
4  52672  100724             ALABAMA STATE UNIVERSITY     AL          NaN   

   HCM2  main  NUMBRANCH                                   PREDDEG  \
0     0  True          1  Predominantly bachelor's-degree granting   
1     0  True          1  Predominantly bachelor's-degree granting   
2     0  True          1  Predominantly bachelor's-degree granting   
3     0  True          1  Predominantly bachelor's-degree granting   
4     0  True          1  Predominantly bachelor's-degree granting   

             CONTROL  ...  HI_INC_DEBT_N DEP_DEBT_N IND_DEBT_N PELL_DEBT_N  \
0             Public  ...          234.0     2384.0      565.0      2400.0   
1             Public  ...          592.0     2913.0     1726.0      2805.0   
2  Private nonprofit  ...            NaN        NaN      325.0       254.0   
3             Public  ...          282.0     1120.0      831.0      1172.0   
4             Public  ...          207.0     2988.0      637.0      3087.0   

  NOPELL_DEBT_N  FEMALE_DEBT_N  MALE_DEBT_N  FIRSTGEN_DEBT_N  \
0         554.0         1516.0       1325.0            938.0   
1        1849.0         2921.0       1567.0           1662.0   
2           NaN          157.0        181.0            162.0   
3         783.0         1071.0        828.0            653.0   
4         548.0         1943.0       1563.0           1181.0   

   NOTFIRSTGEN_DEBT_N  Year  
0              1476.0  2004  
1              2455.0  2004  
2               131.0  2004  
3              1132.0  2004  
4              1655.0  2004  

[5 rows x 41 columns]

In [3]:
df['y'] = np.where(df.CONTROL == 'Public', 1, 0)


In [4]:
df.dtypes

Id                      int64
UNITID                  int64
INSTNM                 object
STABBR                 object
AccredAgency           object
HCM2                    int64
main                     bool
NUMBRANCH               int64
PREDDEG                object
CONTROL                object
region                 object
LOCALE                 object
CCBASIC                object
CCUGPROF               object
RELAFFIL               object
PCIP01                float64
CURROPER                 bool
NPT4_PUB              float64
NPT4_PRIV             float64
CDR3                  float64
DEATH_YR2_RT          float64
DEATH_YR3_RT          float64
DEATH_YR4_RT          float64
DEATH_YR6_RT          float64
DEATH_YR8_RT          float64
DEBT_MDN              float64
DEBT_N                float64
GRAD_DEBT_N           float64
WDRAW_DEBT_N          float64
LO_INC_DEBT_N         float64
MD_INC_DEBT_N         float64
HI_INC_DEBT_N         float64
DEP_DEBT_N            float64
IND_DEBT_N

In [5]:
feats = df[['y', 'NUMBRANCH', 'DEBT_MDN', 'DEBT_N', 'LO_INC_DEBT_N', 'MD_INC_DEBT_N', 'HI_INC_DEBT_N', 'FEMALE_DEBT_N', 'MALE_DEBT_N']]
feats = feats.dropna(axis=0)
feats.groupby('y').agg('count')

NUMBRANCH  DEBT_MDN  DEBT_N  LO_INC_DEBT_N  MD_INC_DEBT_N  HI_INC_DEBT_N  \
y                                                                             
0      15792     15792   15792          15792          15792          15792   
1      12667     12667   12667          12667          12667          12667   

   FEMALE_DEBT_N  MALE_DEBT_N  
y                              
0          15792        15792  
1          12667        12667

In [6]:
split = int(len(feats)/2)
dftrain = feats.iloc[:split:, :].copy()
dftest = feats.iloc[split:, :].copy()
Xtrain = dftrain.drop('y', axis=1)
Xtest = dftest.drop('y', axis=1)
Ytrain = dftrain['y']
Ytest = dftest['y']


print(Xtrain.shape, Xtest.shape, Ytrain.shape, Ytest.shape)

(14229, 8) (14230, 8) (14229,) (14230,)


In [7]:
lr = linear_model.LogisticRegression(penalty='l2', C=1e9)
lr = lr.fit(Xtrain, Ytrain)
print('\n Percentage accuracy vanilla')
print(lr.score(Xtest, Ytest))

ridge = linear_model.LogisticRegression(penalty='l2', C=1)
ridgefit = ridge.fit(Xtrain, Ytrain)
print('\n Percentage accuracy ridge')
print(ridgefit.score(Xtest, Ytest))


lasso = linear_model.LogisticRegression(penalty='l1', C=1)
lassfit = lasso.fit(Xtrain, Ytrain)
print('\n Percentage accuracy lasso')
print(lassfit.score(Xtest, Ytest))

c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



 Percentage accuracy vanilla
0.7522839072382291


c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



 Percentage accuracy ridge
0.7545326774420239


c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



 Percentage accuracy lasso
0.8560787069571328


c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [8]:
for C in range(1,20,1):
    C = C/10
    ridge = linear_model.LogisticRegression(penalty='l2', C=C, solver='liblinear')
    ridgefit = ridge.fit(Xtrain, Ytrain)
    print(ridgefit.score(Xtest, Ytest))

0.822487702037948
0.7520028109627548
0.7549543218552354
0.7523541813070976
0.7713984539704849
0.816865776528461
0.7530569219957836
0.7591004919184821
0.7521433591004919
0.7545326774420239
0.7479971890372452
0.7469430780042164
0.7839775122979621
0.826563598032326
0.7472241742796908
0.823330990864371
0.7517919887561489
0.7688685874912158
0.7513000702740689


for C in range(1,5,1):
    C = C/10
    lasso = linear_model.LogisticRegression(penalty='l1', C=C, solver='liblinear', max_iter=200)
    lassfit = lasso.fit(Xtrain, Ytrain)
    print(lassfit.score(Xtest, Ytest))

In [9]:
lr.coef_

array([[-2.94178343e-01, -8.06468837e-05,  8.12880554e-03,
         3.57444312e-02,  3.68252000e-02,  3.69371662e-02,
        -4.48669192e-02, -4.48872534e-02]])

In [10]:
ridgefit.coef_

array([[-2.79730246e-01, -8.38442596e-05,  8.08434261e-03,
         3.66301098e-02,  3.77581603e-02,  3.78529296e-02,
        -4.57466320e-02, -4.57566609e-02]])

In [11]:
lassfit.coef_

array([[-7.07749589e-01, -3.25678024e-04,  8.66141108e-03,
         6.47117712e-03,  6.48711139e-03,  8.71299530e-03,
        -1.54370079e-02, -1.56344448e-02]])

In [12]:
#I suspect the high value of the features is making all the coefficients low, even when they are meaningful. 
#I'm going to scale down the features without changing anything else and see if that gives more intuitive coefficients

In [13]:
feats.head()

y  NUMBRANCH  DEBT_MDN  DEBT_N  LO_INC_DEBT_N  MD_INC_DEBT_N  \
0  1          1   13625.0  3092.0         1872.0          843.0   
1  1          1   10500.0  4938.0         2566.0         1481.0   
3  1          1   10500.0  2036.0          970.0          699.0   
4  1          1   11000.0  3896.0         2552.0          866.0   
5  1          1   14500.0  5786.0         2248.0         1961.0   

   HI_INC_DEBT_N  FEMALE_DEBT_N  MALE_DEBT_N  
0          234.0         1516.0       1325.0  
1          592.0         2921.0       1567.0  
3          282.0         1071.0        828.0  
4          207.0         1943.0       1563.0  
5         1311.0         2951.0       2427.0

In [20]:
scaler = preprocessing.StandardScaler()
#featcols = pd.DataFrame()
featsScaled = scaler.fit_transform(feats.iloc[:,1:])
featsScaled = pd.DataFrame(featsScaled, index=feats.index)
featsScaled.insert(0,'y',feats['y'])
featsScaled.columns = feats.columns
featsScaled.head()

c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\preprocessing\data.py:617: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


y  NUMBRANCH  DEBT_MDN    DEBT_N  LO_INC_DEBT_N  MD_INC_DEBT_N  \
0  1  -0.362238  0.705178 -0.229582      -0.220108      -0.228069   
1  1  -0.362238  0.028469 -0.191255      -0.197233      -0.182016   
3  1  -0.362238  0.028469 -0.251507      -0.249840      -0.238463   
4  1  -0.362238  0.136742 -0.212889      -0.197695      -0.226409   
5  1  -0.362238  0.894656 -0.173649      -0.207715      -0.147368   

   HI_INC_DEBT_N  FEMALE_DEBT_N  MALE_DEBT_N  
0      -0.293905      -0.223919    -0.239186  
1      -0.210635      -0.181252    -0.223619  
3      -0.282740      -0.237432    -0.271156  
4      -0.300185      -0.210952    -0.223876  
5      -0.043397      -0.180341    -0.168299

In [15]:
split = int(len(featsScaled)/2)
dftrain = featsScaled.iloc[:split:, :].copy()
dftest = featsScaled.iloc[split:, :].copy()
Xtrain = dftrain.drop('y', axis=1)
Xtest = dftest.drop('y', axis=1)
Ytrain = dftrain['y']
Ytest = dftest['y']


print(Xtrain.shape, Xtest.shape, Ytrain.shape, Ytest.shape)

(14229, 8) (14230, 8) (14229,) (14230,)


In [16]:
lr = linear_model.LogisticRegression(penalty='l2', C=1e9)
lr = lr.fit(Xtrain, Ytrain)
print('\n Percentage accuracy vanilla')
print(lr.score(Xtest, Ytest))

ridge = linear_model.LogisticRegression(penalty='l2', C=1)
ridgefit = ridge.fit(Xtrain, Ytrain)
print('\n Percentage accuracy ridge')
print(ridgefit.score(Xtest, Ytest))


lasso = linear_model.LogisticRegression(penalty='l1', C=1)
lassfit = lasso.fit(Xtrain, Ytrain)
print('\n Percentage accuracy lasso')
print(lassfit.score(Xtest, Ytest))

c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



 Percentage accuracy vanilla
0.8399156711173577

 Percentage accuracy ridge
0.8443429374560787


c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



 Percentage accuracy lasso
0.8514406184118061


c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [17]:
display(lr.coef_)

display(ridgefit.coef_)

display(lassfit.coef_)

array([[  -20.90840203,    -1.8774077 ,   562.43390308,  1252.1173084 ,
          599.15127185,   187.3902222 , -1788.63671087,  -848.62322754]])

array([[-12.62513685,  -1.29593041,   1.92377261,  -3.35452832,
          2.87514178,   8.30942367,  -2.02502431,  -3.80501949]])

array([[ -15.15230119,   -1.38624807,  173.0963632 ,    0.        ,
           1.1743363 ,    9.65140107, -122.58082876,  -61.56795087]])

In [21]:
#Much more insightful. Sure enough, classic linear regression has some very large coefficients.
#Since Lasso is indicating that I can remove 1-3 features, I'm going to do that, then rereun all the models.

In [22]:
featsScaled.head(1)

y  NUMBRANCH  DEBT_MDN    DEBT_N  LO_INC_DEBT_N  MD_INC_DEBT_N  \
0  1  -0.362238  0.705178 -0.229582      -0.220108      -0.228069   

   HI_INC_DEBT_N  FEMALE_DEBT_N  MALE_DEBT_N  
0      -0.293905      -0.223919    -0.239186

In [27]:
feats2 = featsScaled.drop('LO_INC_DEBT_N', axis=1)
split = int(len(feats2)/2)
dftrain = feats2.iloc[:split:, :].copy()
dftest = feats2.iloc[split:, :].copy()
Xtrain = dftrain.drop('y', axis=1)
Xtest = dftest.drop('y', axis=1)
Ytrain = dftrain['y']
Ytest = dftest['y']


print(Xtrain.shape, Xtest.shape, Ytrain.shape, Ytest.shape)

(14229, 7) (14230, 7) (14229,) (14230,)


In [28]:
lr = linear_model.LogisticRegression(penalty='l2', C=1e9)
lr = lr.fit(Xtrain, Ytrain)
print('\n Percentage accuracy vanilla')
print(lr.score(Xtest, Ytest))

ridge = linear_model.LogisticRegression(penalty='l2', C=1)
ridgefit = ridge.fit(Xtrain, Ytrain)
print('\n Percentage accuracy ridge')
print(ridgefit.score(Xtest, Ytest))


lasso = linear_model.LogisticRegression(penalty='l1', C=1)
lassfit = lasso.fit(Xtrain, Ytrain)
print('\n Percentage accuracy lasso')
print(lassfit.score(Xtest, Ytest))

c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



 Percentage accuracy vanilla
0.8514406184118061

 Percentage accuracy ridge
0.8451159522136331


c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



 Percentage accuracy lasso
0.8519325368938861


c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


In [33]:
display(lr.coef_)

display(ridgefit.coef_)

display(lassfit.coef_)

array([[ -20.69411798,   -1.62580291,  925.08275741,   -6.80273625,
          12.74210349, -651.33567952, -307.38794318]])

array([[-13.46677621,  -1.33281151,   2.55221569,   4.66607391,
          9.27611518,  -5.80938307,  -6.37455966]])

array([[ -17.16008746,   -1.45908715,  399.28792733,   -2.69594048,
          10.23750831, -279.3460746 , -134.61123178]])

In [30]:
#Test ridge for different values of lambda
for C in range(1,20,1):
    C = C/10
    ridge = linear_model.LogisticRegression(penalty='l2', C=C, solver='liblinear')
    ridgefit = ridge.fit(Xtrain, Ytrain)
    print(ridgefit.score(Xtest, Ytest))

0.8345748418833451
0.8394237526352776
0.8421644413211525
0.843429374560787
0.8444834855938159
0.8445537596626844
0.8450456781447646
0.845326774420239
0.8452565003513703
0.8451159522136331
0.844975404075896
0.8450456781447646
0.8451159522136331
0.8454673225579761
0.845818692902319
0.8455375966268447
0.8457484188334504
0.8456781447645819
0.8456078706957133


In [31]:
for C in range(1,22,4):
    C = C/10
    lasso = linear_model.LogisticRegression(penalty='l1', C=C, solver='liblinear', max_iter=200)
    lassfit = lasso.fit(Xtrain, Ytrain)
    print(lassfit.score(Xtest, Ytest))

0.848208011243851
0.8470836261419536


c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.8537596626844695
0.8546029515108925


c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.8560787069571328
0.8562895291637386


c:\users\greg\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\svm\base.py:922: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


# At first,
Lasso appears to be better while there are bad features, due to its inherent feature selection. However, once I changed the featureset and reran all models with the new features, ridge appears to be best. All 3 are scoring similarly on accuracy, but Ridge actually has far lower coefficients, leading me to believe that may be the most versatile model for new data.

Below I reproduce with Statsmodels. 

In [41]:
logit = sm.Logit(Ytrain, Xtrain)
logit.score_obs(Xtest)

ValueError: shapes (14229,7) and (14230,7) not aligned: 7 (dim 1) != 14230 (dim 0)

In [ ]:
logit.fit().params